kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argocd-prod
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30082
    hostPort: 30082
    protocol: TCP
- role: worker
- role: worker